[build]
  base = "."
  publish = "dist/public"
  command = "echo 'NETLIFY DEBUG - VITE_ENABLE_ADMIN='$VITE_ENABLE_ADMIN && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=. --silent"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200